"""
Phrase expansions for multi-token substitution.

A single substitution destroys two pairs: -2.0 on the numerator.
Replacing one token with k tokens destroys the same two pairs AND
raises gamma*T by 0.5(k-1), giving -2 - 0.5(k-1). At k=5 that is
-4.0, twice as effective per edit.

Each expansion is grammatically interchangeable with its trigger
in any context, so the attack never has to reason about what
follows.
"""

EXPANSIONS = {
    "said": ["went on to say", "said in a statement", "noted at the time"],
    "says": ["goes on to say", "says in a statement"],
    "added": ["went on to add", "added in a statement"],
    "noted": ["went on to note", "made a note of"],
    "reported": ["went on to report", "said in its report"],
    "announced": ["went on to announce", "made an announcement about"],
    "stated": ["went on to state", "put on record"],
    "told": ["went on to tell", "said in remarks to"],
    "explained": ["went on to explain", "gave an explanation of"],
    "confirmed": ["went on to confirm", "gave confirmation of"],
    "warned": ["went on to warn", "issued a warning about"],
    "argued": ["went on to argue", "made the argument that"],
    "claimed": ["went on to claim", "made the claim that"],
    "suggested": ["went on to suggest", "made the suggestion that"],
    "described": ["went on to describe", "gave a description of"],
    "wrote": ["went on to write", "put in writing"],
    "asked": ["went on to ask", "put the question of"],
    "showed": ["went on to show", "served to show"],
    "found": ["went on to find", "came to find"],
    "will": ["is expected to", "is set to", "is on track to"],
    "would": ["was expected to", "was set to"],
    "can": ["is able to", "has the ability to"],
    "could": ["was able to", "had the ability to"],
    "may": ["is likely to", "stands a chance to"],
    "might": ["was likely to", "stood a chance to"],
    "must": ["is required to", "has an obligation to"],
    "should": ["is supposed to", "ought to go and"],
    "but": ["having said that", "that said"],
    "and": ["as well as", "along with"],
    "because": ["on account of the fact that", "owing to the fact that"],
    "although": ["in spite of the fact that", "despite the fact that"],
    "while": ["at the same time that", "over the time that"],
    "since": ["from the time that", "given the fact that"],
    "if": ["in the event that", "on the chance that"],
    "when": ["at the time that", "at the point when"],
    "after": ["in the wake of", "following on from"],
    "before": ["in advance of", "ahead of the time of"],
    "during": ["over the course of", "in the period of"],
    "through": ["by way of", "by means of"],
    "about": ["in relation to", "with regard to"],
    "with": ["along with", "together with"],
    "without": ["in the absence of", "with no sign of"],
    "despite": ["in spite of", "regardless of"],
    "unless": ["except in the case that", "other than when"],
    "whether": ["in the matter of whether", "on the question of whether"],
    "also": ["in addition to this", "on top of that"],
    "however": ["having said that", "with that being said"],
    "therefore": ["for that reason", "as a result of this"],
    "instead": ["in place of that", "as an alternative"],
    "more": ["a greater amount of", "a larger share of"],
    "most": ["the majority of", "the greater part of"],
    "many": ["a large number of", "a great many"],
    "much": ["a great deal of", "a large amount of"],
    "few": ["a small number of", "not a great many"],
    "some": ["a number of", "a portion of"],
    "all": ["the whole of", "each and every one of"],
    "each": ["every one of", "each and every"],
    "both": ["the two of", "each of the two"],
    "very": ["to a great extent", "in a great way"],
    "almost": ["very nearly", "all but"],
    "nearly": ["very close to", "just short of"],
    "only": ["no more than", "nothing other than"],
    "just": ["no more than", "nothing but"],
    "now": ["at this point in time", "as things stand"],
    "then": ["at that point in time", "at that stage"],
    "soon": ["before long", "in short order"],
    "later": ["at a later point", "further down the line"],
    "often": ["on a frequent basis", "time and time again"],
    "always": ["at all times", "on every occasion"],
    "never": ["at no point", "on no occasion"],
    "still": ["even at this point", "as things remain"],
    "already": ["as of this point", "by this stage"],
    "recently": ["in recent times", "over the recent period"],
    "currently": ["at the current time", "as of right now"],
    "finally": ["in the end", "at the last"],
    "increased": ["posted an increase of", "showed an increase of"],
    "decreased": ["posted a decrease of", "showed a decline of"],
    "rose": ["went on to rise", "posted a rise of"],
    "fell": ["went on to fall", "posted a fall of"],
    "grew": ["went on to grow", "posted growth of"],
    "used": ["made use of", "put to use"],
    "helped": ["went on to help", "played a part in helping"],
    "began": ["went on to begin", "made a start on"],
    "started": ["made a start on", "got under way with"],
    "continued": ["went on to continue", "carried on with"],
    "ended": ["came to an end", "drew to a close"],
    "included": ["went on to include", "made room for"],
    "provided": ["went on to provide", "made available"],
    "offered": ["went on to offer", "made an offer of"],
    "received": ["went on to receive", "took receipt of"],
    "created": ["went on to create", "brought into being"],
    "made": ["went on to make", "brought about"],
    "took": ["went on to take", "made a move to take"],
    "gave": ["went on to give", "made a gift of"],
    "came": ["went on to come", "made its way"],
    "became": ["went on to become", "came to be"],
    "remained": ["went on to remain", "carried on as"],
    "appeared": ["went on to appear", "made an appearance"],
    "seemed": ["gave the impression of being", "came across as"],
    "expected": ["went on to expect", "had expectations of"],
    "believed": ["went on to believe", "held the belief that"],
    "wanted": ["went on to want", "had a wish for"],
    "needed": ["went on to need", "had a need for"],
    "tried": ["went on to try", "made an attempt to"],
    "decided": ["went on to decide", "came to a decision to"],
    "agreed": ["went on to agree", "came to an agreement to"],
    "planned": ["went on to plan", "made plans to"],
    "called": ["went on to call", "made a call to"],
    "worked": ["went on to work", "put in work"],
    "played": ["went on to play", "took a part in"],
    "built": ["went on to build", "put together"],
    "bought": ["went on to buy", "made a purchase of"],
    "sold": ["went on to sell", "made a sale of"],
    "paid": ["went on to pay", "made a payment of"],
    "spent": ["went on to spend", "laid out"],
    "won": ["went on to win", "came away with"],
    "lost": ["went on to lose", "came away without"],
    "held": ["went on to hold", "kept hold of"],
    "kept": ["went on to keep", "held on to"],
    "left": ["went on to leave", "took leave of"],
    "moved": ["went on to move", "made a move"],
    "brought": ["went on to bring", "came in with"],
    "set": ["went on to set", "put in place"],
}
