"""
Pruned expansion table.

Removed: triggers whose grammatical role genuinely
varies -- function words with multiple syntactic roles,
quantifiers, light verbs, and the ambiguous modals.

Kept: reporting verbs (fixed complement structure),
clause connectives (position fixes the role), temporal
adverbs, and prepositions with stable scope.
"""

EXPANSIONS = {
    'added': ['went on to add', 'added in a statement'],
    'after': ['in the wake of', 'following on from'],
    'agreed': ['went on to agree', 'came to an agreement to'],
    'already': ['as of this point', 'by this stage'],
    'also': ['in addition to this', 'on top of that'],
    'although': ['in spite of the fact that', 'despite the fact that'],
    'always': ['at all times', 'on every occasion'],
    'announced': ['went on to announce', 'made an announcement about'],
    'appeared': ['went on to appear', 'made an appearance'],
    'argued': ['went on to argue', 'made the argument that'],
    'asked': ['went on to ask', 'put the question of'],
    'became': ['went on to become', 'came to be'],
    'because': ['on account of the fact that', 'owing to the fact that'],
    'before': ['in advance of', 'ahead of the time of'],
    'began': ['went on to begin', 'made a start on'],
    'believed': ['went on to believe', 'held the belief that'],
    'bought': ['went on to buy', 'made a purchase of'],
    'built': ['went on to build', 'put together'],
    'but': ['having said that', 'that said'],
    'called': ['went on to call', 'made a call to'],
    'claimed': ['went on to claim', 'made the claim that'],
    'confirmed': ['went on to confirm', 'gave confirmation of'],
    'continued': ['went on to continue', 'carried on with'],
    'created': ['went on to create', 'brought into being'],
    'currently': ['at the current time', 'as of right now'],
    'decided': ['went on to decide', 'came to a decision to'],
    'decreased': ['posted a decrease of', 'showed a decline of'],
    'described': ['went on to describe', 'gave a description of'],
    'despite': ['in spite of', 'regardless of'],
    'during': ['over the course of', 'in the period of'],
    'ended': ['came to an end', 'drew to a close'],
    'expected': ['went on to expect', 'had expectations of'],
    'explained': ['went on to explain', 'gave an explanation of'],
    'fell': ['went on to fall', 'posted a fall of'],
    'finally': ['in the end', 'at the last'],
    'found': ['went on to find', 'came to find'],
    'grew': ['went on to grow', 'posted growth of'],
    'helped': ['went on to help', 'played a part in helping'],
    'however': ['having said that', 'with that being said'],
    'if': ['in the event that', 'on the chance that'],
    'included': ['went on to include', 'made room for'],
    'increased': ['posted an increase of', 'showed an increase of'],
    'instead': ['in place of that', 'as an alternative'],
    'later': ['at a later point', 'further down the line'],
    'lost': ['went on to lose', 'came away without'],
    'needed': ['went on to need', 'had a need for'],
    'never': ['at no point', 'on no occasion'],
    'noted': ['went on to note', 'made a note of'],
    'now': ['at this point in time', 'as things stand'],
    'offered': ['went on to offer', 'made an offer of'],
    'often': ['on a frequent basis', 'time and time again'],
    'paid': ['went on to pay', 'made a payment of'],
    'planned': ['went on to plan', 'made plans to'],
    'played': ['went on to play', 'took a part in'],
    'provided': ['went on to provide', 'made available'],
    'received': ['went on to receive', 'took receipt of'],
    'recently': ['in recent times', 'over the recent period'],
    'remained': ['went on to remain', 'carried on as'],
    'reported': ['went on to report', 'said in its report'],
    'rose': ['went on to rise', 'posted a rise of'],
    'said': ['went on to say', 'said in a statement', 'noted at the time'],
    'says': ['goes on to say', 'says in a statement'],
    'seemed': ['gave the impression of being', 'came across as'],
    'showed': ['went on to show', 'served to show'],
    'since': ['from the time that', 'given the fact that'],
    'sold': ['went on to sell', 'made a sale of'],
    'soon': ['before long', 'in short order'],
    'spent': ['went on to spend', 'laid out'],
    'started': ['made a start on', 'got under way with'],
    'stated': ['went on to state', 'put on record'],
    'still': ['even at this point', 'as things remain'],
    'suggested': ['went on to suggest', 'made the suggestion that'],
    'then': ['at that point in time', 'at that stage'],
    'therefore': ['for that reason', 'as a result of this'],
    'through': ['by way of', 'by means of'],
    'told': ['went on to tell', 'said in remarks to'],
    'tried': ['went on to try', 'made an attempt to'],
    'unless': ['except in the case that', 'other than when'],
    'used': ['made use of', 'put to use'],
    'wanted': ['went on to want', 'had a wish for'],
    'warned': ['went on to warn', 'issued a warning about'],
    'when': ['at the time that', 'at the point when'],
    'whether': ['in the matter of whether', 'on the question of whether'],
    'while': ['at the same time that', 'over the time that'],
    'will': ['is expected to', 'is set to', 'is on track to'],
    'won': ['went on to win', 'came away with'],
    'worked': ['went on to work', 'put in work'],
    'would': ['was expected to', 'was set to'],
    'wrote': ['went on to write', 'put in writing'],
}
